### ISSUE TITLE
[Meta] ember-application-visit

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#11291]
Placeholder; see #11289

- [ ] Initializers are not run for `autoboot: false` (see https://github.com/emberjs/ember.js/pull/11289#issuecomment-105960488)
- [ ] `transitionTo` causes `App.visit` to reject with `TransitionAborted`
- [ ] Need a lower-level API to create an `ApplicationInstance`?

**Comment by chancancode** [comment]
### Explanation for (2)

I'm working on redirects for `ember-cli-fastboot`. Basically, you need to wait for the instance to boot, call `handleURL` on it, wait for it to settle, then observe the final URL. If the final URL is different from the initial URL, we want to issue a 302 to (we also need to add a way to signal a 301, but that's a different story).

Currently, if you `visit` an initial URL that redirects to a different URL (via `transitionTo`/`replaceWith`), the `handleURL` promise will reject with `TransitionAborted`, which also means to that you will never get a reference to the application instance (to check URL, etc).

### Explanation for (3)

While (2) can be solved by wrapping `handleURL` inside `visit` to handle the rejection (or call a different method on the router), and while `visit` is a good first step because it's relatively clear/easy to define (and we have a real use case to test it), I think in the long run we are better off providing more fine-grained API to bootstrap an instance.

See also https://github.com/emberjs/ember.js/pull/11289#issuecomment-107299448

**Comment by mixonic** [comment]
@chancancode this should perhaps be updated

**Comment by pixelhandler** [comment]
@chancancode is this still something that you're working on?

**Comment by Serabe** [comment]
@chancancode can you please give an update on this and close it if it is not longer needed? Thank you!

**Comment by pixelhandler** [comment]
@chancancode perhaps this needs to be closed and reopen if necessary when work begins?

**Comment by chancancode** [comment]
Sorry, I don't remember the context but i suspect it's fixed now 😞
