### ISSUE TITLE
Glimmer Components Checklist

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#12129]
Post merge pending items from https://github.com/emberjs/ember.js/pull/12011:

- [ ] Fix top-level `{{partial}}` case (0604db16ea85496b294d31f4289fbf1687924e89)
- [ ] Make sure that people don't accidentally use old-style APIs for top-level elements in GlimmerComponent (`tagName`)
- [ ] Refactor to separate conceptually different code paths that happen to share code, such as...
  - [ ] build-component-template
  - [ ] component node manager?
- [ ] make recursive invocation work (`<my-foo>` component as the top-level element inside `<my-bar>`'s layout)
- [ ] discuss a path for properties vs. attributes being plausibly aligned between normal elements and components
- [ ] Make sure `elementId` is set on GlimmerComponent
- [ ] Fix skipped tests.
- [ ] Make GlimmerComponent `isComponentFactory`
- [ ] Export `GlimmerComponent` as a module
- [ ] Add flag to allow a component author to use new-semantics and provide a deprecation when the component is invoked with curlies (providing a bridge from `{{foo-bar blah="baz"}}` to `<foo-bar blah="baz"></foo-bar>`).

**Comment by chancancode** [comment]
- [ ] Make GlimmerComponent `isComponentFactory`
- [ ] Export `GlimmerComponent` as a module

**Comment by mixonic** [comment]
@rwjblue can this be closed?

**Comment by rwjblue** [comment]
Ya. Will close for now, if/when we start pushing on GlimmerComponent again, we can reevaluate.
