### ISSUE TITLE
ember-container-inject-owner - Checklist

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#12555]
- [x] Implement `FakeContainer` concept discussed in https://github.com/emberjs/ember.js/pull/11874.  This will help ensure full access to the container is possible, with a complete valid set of deprecations for each method or property accessed. The primary scenario that this affects that does not already have a deprecation is when the factory being instantiated does not have `.extend`.
- [x] Ensure ember-test-helpers detects `getOwner` / `setOwner` and functions properly with this feature on or off.
- [x] Document `getOwner` and `setOwner` functions in API docs. https://github.com/emberjs/ember.js/pull/12562
- [x] Audit and update guides details. I'm fairly sure we do not have any discussion of `this.container` in the guides (because it has been considered private API for ever), but we might want to add some prose to the dependency injection? https://github.com/emberjs/guides/pull/938, needs another PR to explain `getOwner` usage.
- [x] Update ember-data to ensure deprecations are not triggered. https://github.com/emberjs/data/pull/3912
- [x] Add deprecation guide entry for the `this.container` deprecation (added in https://github.com/emberjs/website/pull/2409) (and cross link the deprecation URL (done in https://github.com/emberjs/ember.js/pull/12604)
- [x] Update liquid-fire to prevent deprecations. https://github.com/ef4/liquid-fire/pull/388
- [x] Update ember-i18n https://github.com/jamesarosen/ember-i18n/pull/336

**Comment by dgeb** [comment]
Looks complete to me. Thanks for putting together this list, @rwjblue.

**Comment by mixonic** [comment]
@dgeb I will attempt docs for this stuff tonight and guides review. I hope that can free you up for some of the more tricky bits.

**Comment by dgeb** [comment]
@mixonic thanks - you're the best! Ping me if you have questions about the new stuff.

**Comment by rwjblue** [comment]
Feature is enabled by default.  I am working on ember-test-helpers updates to make sure this is handled properly.

**Comment by dgeb** [comment]
Sounds good. I'll tackle the `FakeContainer`.

**Comment by mixonic** [comment]
FWIW guides have been given a cursory review, though I have not undertaken any long prose about "dynamic lookup" which I think may be the only app-based use case for `getOwner` (other cases being around testing, and usually testing internals).

**Comment by rwjblue** [comment]
Thanks @mixonic

**Comment by rwjblue** [comment]
I just published a polyfill that addons can use (https://travis-ci.org/rwjblue/ember-getowner-polyfill) pretty easily.

**Comment by rwjblue** [comment]
@tim-evans and I are working on updating ember-test-helpers to provide `owner` properly.

**Comment by rwjblue** [comment]
ember-qunit and ember-mocha versions have been released that take advantage of the new feature (checking the `ember-test-helpers` item off on the checklist).

**Comment by rwjblue** [comment]
I took some time to update ember-data in https://github.com/emberjs/data/pull/3912. I'm hoping that those changes can make it into Ember Data 2.2.0 (but Ember Data 2.3.0 would be perfectly fine).

**Comment by rwjblue** [comment]
ember-data PR is merged (checked off above), and liquid-fire PR is submitted (https://github.com/ef4/liquid-fire/pull/388).

**Comment by rwjblue** [comment]
@dgeb - Have you begun work on the `FakeContainer` bullet point?

**Comment by dgeb** [comment]
@rwjblue - sorry for the delay - I will try to wrap that up tomorrow

**Comment by rwjblue** [comment]
Added URL to the deprecation in https://github.com/emberjs/ember.js/pull/12604, and the deprecation guide in https://github.com/emberjs/website/pull/2409.

**Comment by rwjblue** [comment]
@mixonic did the initial guide audit (mentioned in https://github.com/emberjs/ember.js/issues/12555#issuecomment-154863763) and I just created https://github.com/emberjs/guides/issues/982 to track updating the DI page with a few mentions of `Ember.getOwner`, so I am checking that item off for now.

**Comment by rwjblue** [comment]
Updated ember-i18n in https://github.com/jamesarosen/ember-i18n/pull/336.

**Comment by dgeb** [comment]
Implemented fake container injection in #12609

**Comment by rwjblue** [comment]
Thanks @dgeb, that fix is merged completing the last item on this checklist.  Closing (please let me know if I have forgotten something).
