### ISSUE TITLE
Glimmer Big-Picture Integration Checklist

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#12907]
We will try to keep this up-to-date during integration. It enumerates the big-picture integration items.

If you hit a not-yet-completed item on this list while trying to help, it's probably better to wait for the initial integration work to finish. On the flip side, if initial integration work for a given feature has finished, it's probably fine to smooth out edge cases and do polish work.

* [x] top-level templates
  * [x] `{{foo.bar}}` for basic POJOs ~~#12901~~
  * [x] `{{foo.bar}}` using `Ember.get` (computed properties, etc.) ~~#12901~~
  * [x] Handle `{{foo}}` where `foo` resolves to `undefined`, `null`, etc ~~#13141~~
  * [x] Align glimmer and ember semantics for attrs vs props
* [x] syntax
  * [x] `{{#if}}` ~~#12912~~, ~~#12914~~ (need help reviewing/porting the rest of the tests)
  * [x] `{{#unless}}` ~~#12912~~, ~~#12914~~ (need help reviewing/porting the rest of the tests)
  * [x] `{{#with}}` ~~#12919~~, ~~#12927~~
  * [x] `{{#each}}` ~~#13048~~
  * [x] `{{#each-in}}`
* [x] helpers
  * [x] "simple" (shorthand/function) helpers ~~#12910~~
  * [x] "class-based" ("stateful") helpers ~~#13087~~
  * [x] builtin helpers ~~#12910~~ (e.g. `{{concat}}`)
    * [x] `if` ~~#12920~~ ~~#13009~~
    * [x] `unless` ~~#13019~~ ~~#13092~~
    * [x] `hash` ~~#13093~~
    * [x] `unbound` #13137
    * [x] `hasBlock`
    * [x] `link-to`
  * [x] user helpers lookup ~~#12917~~ (need help reviewing/porting the rest of the tests)
* [x] components
  * [x] curly components ~~#12948~~ ~~#12962~~ (need help reviewing/porting the rest of the tests – note that a lot of features, are not implemented yet: see below)
  * [ ] glimmer components (`<angle-brackets>`)
  * [x] `{{component}}` ~~#13057~~
  * [x] view state transition ~~#13008~~
  * [x] view hierarchy ~~#12978~~
  * [x] teardown ~~#13008~~
  * [x] old lifecycle hooks (`didInsertElement`, etc.) #13156 #13168
  * [x] new lifecycle hooks (`willRender`, etc.)
  * [x] `attributeBindings`, `classNameBindings`, `classNames` ~~#13160~~
  * [x] `tagName` ~~#13145~~
  * [x] `this.element` ~~#12975~~
  * [x] `this.$()` ~~#13008~~
  * [x] `{{yield}}`-ing block arguments
* [x] partials
* [x] `{{render}}`
* [x] element helpers (`{{action}}` etc.)
* [x] ~~legacy functionality when using addons~~
  * [ ] ~~`{{view}}` #12978~~
  * [ ] ~~`{{view.prop}}` #12978~~
  * [ ] ~~`{{controller}}`~~
* [x] `{{outlet}}` ~~#13067~~
* [x] runloop integration (auto rerender after `set`, etc – this is shimmed by forcing a rerender inside `this.runTask` in the test cases, so it shouldn't be an immediate blocker)
* [x] framework-level integration (using `ember-glimmer` to render route templates, injecting the `ember-glimmer` renderer to components/views etc)
* [x] make it possible to switch between the two engines in apps by toggling the feature flag

Available to work on (roughly ordered from easiest to most difficult):

* [x] Add tests for rending `false`, `undefined`, `null` etc in `content-test.js`, similar to https://github.com/emberjs/ember.js/blob/3ee1cfa973229324fe2fcc695c712e02955f05d0/packages/ember-glimmer/tests/integration/syntax/if-unless-test.js#L42-L91. This would fail in glimmer atm, so it needs to be `@htmlbars`.
* [x] Implement inline `if`/`else` helpers (see comments in #12914).
* [x] Port remaining built-in helpers. Should be similar to #12910. Some helpers are easier than the others.
* [x] Implement `{{#with}}` (this is slightly more difficult, but generally follows the footsteps of https://github.com/tildeio/glimmer/pull/61 and #12914).
* [x] Review and port remaining tests in `if_unless_test.js` (see comments in #12914). This requires carefully analysis of the tests and git history digging.

**Comment by chadhietala** [comment]
`{{#with}}` should be updated to reflect #12927

**Comment by chancancode** [comment]
I think we are done here 😁

See #13644 for remaining edge-cases
