### ISSUE TITLE
Glimmer Performance Integration Checklist

### ISSUE THREAD

**Issue by wycats** [emberjs/ember.js#12979]
This is a list of items that aren't strictly required for semantic compatibility, but probably need to happen before we ship.

- [ ] Hook up observers on second hit to a reference
- [ ] Use `isDirty` pervasively throughout the Glimmer code
- [ ] Eliminate the cost of attribute merging on normal elements
- [ ] Basic ConstReference optimization (related to `unbound`)

(related to #12907)
