### ISSUE TITLE
[meta] Improve issue triaging workflow to save core team bandwidth

### ISSUE THREAD

**Issue by acorncom** [emberjs/ember.js#13245]
Per a discussion on Slack, on the `#-learning` channel:

```
acorncom: seems like we could use more folks triaging issues for ember.js (preferably using tags, and potentially given ability to close stale issues) without full write-access to emberjs/ember.js
acorncom: is there some bot (like homu) that allows for that?
acorncom: would love to alleviate the triaging load for core folks without giving me (or others) full-on write access.  not sure I need that responsibility just now ;-)
```

```
rwjblue: I'm not opposed to an issue triage team with access/permissions to close issues
```

Looks like we have a few items that need to be worked out:

- [ ] core team approval (in addition to @rwjblue)
- [ ] finding / building a bot that does what we're after 
- [ ] setting the bot up on this repo

**Comment by rwjblue** [comment]
I think it would be easier to start with a couple "trusted advisors" that would have access to close issues directly.  Unless a bot already exists, I feel that writing one will take much more time than just giving commit to people that we already trust...

**Comment by acorncom** [comment]
Looks like a bot may exist, but it's written in (wait for it ...) PHP :grinning: 
https://github.com/carsonbot/carsonbot

Sounds good on the trusted advisor route as well if we'd prefer that ...

**Comment by rwjblue** [comment]
We discussed this in the core team meeting today, and we are happy to move forward with giving access to folks for issue triage.  I'll try to get in touch with some folks in the #dev-issue-triage channel in slack this coming week...

**Comment by acorncom** [comment]
Cool.  Will close this issue then
