### ISSUE TITLE
Glimmer Pre-flight Checklist

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13644]
![You're closer than you think](http://www.nasa.gov/sites/default/files/styles/ubernode_alt_horiz/public/11572307115_1194957269_o_0.jpg "You're closing in")

Below is the pre-flight checklist to launch Glimmer. If you are going to take a test to fix please leave a comment on this thread. Please mention this issue in your PR so we can track more effectively. 

## Features
- [x] `{{render}}`
- [x] `sendAction` #13532 🔒 @Joelkang
- [x] `{{mut}}` and `{{readonly}}` #13541 🔒 @Joelkang
- [x] `{{input}}` #13615 🔒 @asakusuma
- [x] Closure components 🔒 @zackthehuman
- [x] Local Lookup 🔒 @asakusuma
- [x] `{{each-in}}` 🔒 @Joelkang #13492

## Testing

__Failing Tests__

- [x] [attrs property of a component without a template should not collide with internal structures](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember/tests/component_registration_test.js#L339)
- [x] [Components receive the top-level view as their ownerView](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember/tests/component_registration_test.js#L404)
- [x] [Using {{link-to}} does not cause an exception if it is rendered without a router.js instance](https://github.com/emberjs/ember.js/blob/60461a144d68835ada96ab3db25cca56c25d02c8/packages/ember/tests/helpers/link_to_test.js#L126)
- [x] [The {{link-to}} helper supports 'classNameBindings' with custom values [GH #11699]](https://github.com/emberjs/ember.js/blob/60461a144d68835ada96ab3db25cca56c25d02c8/packages/ember/tests/helpers/link_to_test.js#L512)
- [x] [The Special page returning an error invokes SpecialRoute's error handler](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L769)
- [x] [ApplicationRoute's default error handler can be overridden](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L855)
- [x] [Events are triggered on the controller if a matching action name is implemented](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L1041)
- [x] [Events are triggered on the current state when defined in `actions` object](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L1085)
- [x] [Events defined in `actions` object are triggered on the current state when routes are nested](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L1119)
- [x] [Actions are not triggered on the controller if a matching action name is implemented as a method](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L1195)
- [x] [actions can be triggered with multiple arguments](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L1238)
- [x] [Router accounts for rootURL on page load when using history location](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L1925)
- [x] [Custom Route#serialize method still works [DEPRECATED]](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2099)
- [x] [The template is not re-rendered when the route's context changes](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2167)
- [x] [The template is not re-rendered when two routes present the exact same template & controller](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2209)
- [x] [Route should tear down multiple outlets](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2320)
- [x] [Route supports clearing outlet explicitly](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2381)
- [x] [Route supports clearing outlet using string parameter](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2450) Dies due to `asLayout` not being a thing
- [x] [Route silently fails when cleaning an outlet from an inactive view](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2496) Dies due to `asLayout` not being a thing
- [x] [Specifying non-existent controller name in route#render throws](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2932) Dies due to `asLayout` not being a thing
- [x] [Redirecting with null model doesn't error out](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L2952)
- [x] [Can disconnect a named outlet at the top level](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3333) Dies due to `asLayout` not being a thing
- [x] [Tolerates stacked renders](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3456) Dies due to `asLayout` not being a thing
- [x] [Allows any route to disconnectOutlet another route's templates](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3513) Dies due to `asLayout` not being a thing
- [x] [Slow promises returned from ApplicationRoute#model enter ApplicationLoadingRoute if present](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/substates_test.js#L743)
- [x] [Slow promises returned from ApplicationRoute#model enter application_loading if template present](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/substates_test.js#L769)
- [x] [Rejected promises returned from ApplicationRoute transition into top-level application_error](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/substates_test.js#L997)
- [ ] [Nodes without view instances are instrumented](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember/tests/view_instrumentation_test.js#L52)
- [x] [the default resolver looks up templates in Ember.TEMPLATES](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember-application/tests/system/dependency_injection/default_resolver_test.js#L54)
- [x] [Ember Islands-style setup](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-application/tests/system/visit_test.js#L358)
- [x] [template with data-template-name should add a new template to Ember.TEMPLATES](https://github.com/emberjs/ember.js/blob/fa9866bf71aa5ef00ff661d0cbe4b0e2cf2ac554/packages/ember-templates/tests/bootstrap_test.js#L47) David Hamilton
- [x] [template with id instead of data-template-name should add a new template to Ember.TEMPLATES](https://github.com/emberjs/ember.js/blob/fa9866bf71aa5ef00ff661d0cbe4b0e2cf2ac554/packages/ember-templates/tests/bootstrap_test.js#L53)
- [x] [template without data-template-name or id should default to application](https://github.com/emberjs/ember.js/blob/fa9866bf71aa5ef00ff661d0cbe4b0e2cf2ac554/packages/ember-templates/tests/bootstrap_test.js#L59)
- [x] [ `triggerEvent` with mouseenter triggers native events with simulated X/Y coordinates](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L458)
- [x] [helpers can be chained with then](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L106) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615 
- [x] [Actions inside an outlet go to the associated controller](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/controller_test.js#L52) Pending PR #13532
- [x] [helpers can be chained to each other](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L133) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615
- [x] [helpers don't need to be chained](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L158) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615
- [x] [Nested async helpers](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L183) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615
- [x] [Multiple async helpers](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L210) Potentially fails because #13615 is not merged
- [x] [Helpers nested in thens](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L229) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615
- [x] [visiting a URL that causes another transition should yield the correct URL](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L363) Potentially fails because #13615 is not merged
- [x] [visiting a URL and then visiting a second URL with a transition should yield the correct URL](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-testing/tests/acceptance_test.js#L373) Potentially fails because #13615 is not merged
- [x] [`click` triggers appropriate events in order](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L347) Potentially fails because #13615 is not merged
- [x] [`triggerEvent accepts an optional options hash without context](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L544) Potentially fails because #13615 is not merged
- [x] [Using {{link-to}} does not cause an exception if it is rendered before the router has started routing](https://github.com/emberjs/ember.js/blob/60461a144d68835ada96ab3db25cca56c25d02c8/packages/ember/tests/helpers/link_to_test.js#L104)
- [x] [`triggerEvent can limit searching for a selector to a scope](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L574) Potentially fails because #13615 is not merged
- [x] [`triggerEvent` can be used to trigger arbitrary events](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L604) Potentially fails because #13615 is not merged
- [x] [`fillIn` takes context into consideration](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L633) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615
- [x] [`fillIn` focuses on the element](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L657) ~~Potentially fails because #13615 is not merged~~ Not fixed by #13615
- [x] [`triggerEvent accepts an optional options hash and context](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember-testing/tests/helpers_test.js#L722) Potentially fails because #13615 is not merged
- [x] [includes the current revision in the compiled template](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember-template-compiler/tests/system/compile_test.js#L11) HTMLBars compiler is hardcoded fails because meta it not implemented
- [x] [the template revision is different than the HTMLBars default revision ](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember-template-compiler/tests/system/compile_test.js#L19)
- [x] [sets `isTop` on the provided function](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember-template-compiler/tests/system/template_test.js#L7) HTMLBars compiler is hardcoded fails because meta it not implemented
- [x] [sets `isMethod` on the provided function](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember-template-compiler/tests/system/template_test.js#L15) HTMLBars compiler is hardcoded fails because meta it not implemented
- [ ] [should accept bindings as a string or an Ember.binding](https://github.com/emberjs/ember.js/blob/3cfc9614bbd92ee8e80b6c4894b024f2e14bffae/packages/ember-glimmer/tests/integration/binding_integration_test.js#L8)
- [x] [blacklists href bindings based on protocol](https://github.com/emberjs/ember.js/blob/1be0354068d933065ac542f49d42d73409366a47/packages/ember-glimmer/tests/integration/components/attribute-bindings-test.js#L456) :lock: @zackthehuman
- [x] [should be able to modify a provided attr into local state #11571 / #11559](https://github.com/emberjs/ember.js/blob/ee55672f4fb23055d792f1a2e2a2f1f68a36318d/packages/ember-glimmer/tests/integration/components/attrs-lookup-test.js#L61) Should be addressed as part of #13541
- [x] [getAttr() should return the same value as get()](https://github.com/emberjs/ember.js/blob/ee55672f4fb23055d792f1a2e2a2f1f68a36318d/packages/ember-glimmer/tests/integration/components/attrs-lookup-test.js#L140) Should be addressed as part of #13541
- [x] [Closure components module](https://github.com/emberjs/ember.js/blob/5766360c35587ac13034b86ea7fad1a6cd65a80c/packages/ember-glimmer/tests/integration/components/closure-components-test.js#L7) Should be addressed by @zackthehuman
- [x] [lookup of component takes priority over property](https://github.com/emberjs/ember.js/blob/0f2d9e6caa472b9bfbcafce220e85ebd4d4efc05/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L908)
- [x] [rerendering component with attrs from parent](https://github.com/emberjs/ember.js/blob/0f2d9e6caa472b9bfbcafce220e85ebd4d4efc05/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L1016)  :lock: @chadhietala #13772
- [x] [component should rerender when a property is changed during children\'s rendering](https://github.com/emberjs/ember.js/blob/0f2d9e6caa472b9bfbcafce220e85ebd4d4efc05/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L1969)
- [x] [component helper with actions](https://github.com/emberjs/ember.js/blob/0f2d9e6caa472b9bfbcafce220e85ebd4d4efc05/packages/ember-glimmer/tests/integration/components/dynamic-components-test.js#L402)
- [x] [Local Lookup tests](https://github.com/emberjs/ember.js/blob/5766360c35587ac13034b86ea7fad1a6cd65a80c/packages/ember-glimmer/tests/integration/components/local-lookup-test.js#L30)
- [x] [Inline style tests](https://github.com/emberjs/ember.js/blob/fa9866bf71aa5ef00ff661d0cbe4b0e2cf2ac554/packages/ember-glimmer/tests/integration/content-test.js#L908) :lock: @chadhietala
- [x] [a nice error is shown when a bound action function is undefined and it is passed as attrs.foo](https://github.com/emberjs/ember.js/blob/9a72fea4854f1a12dbd81b7779afd77f99331b7e/packages/ember-glimmer/tests/integration/helpers/closure-action-test.js#L269) May need #13541
- [x] [mut values can be wrapped in actions, are settable](https://github.com/emberjs/ember.js/blob/9a72fea4854f1a12dbd81b7779afd77f99331b7e/packages/ember-glimmer/tests/integration/helpers/closure-action-test.js#L582) Should be covered in #13541
- [x] [mut values can be wrapped in actions, are settable with a curry](https://github.com/emberjs/ember.js/blob/9a72fea4854f1a12dbd81b7779afd77f99331b7e/packages/ember-glimmer/tests/integration/helpers/closure-action-test.js#L626)  Should be covered in #13541
- [x] [objects that define INVOKE can be casted to actions](https://github.com/emberjs/ember.js/blob/9a72fea4854f1a12dbd81b7779afd77f99331b7e/packages/ember-glimmer/tests/integration/helpers/closure-action-test.js#L1058) Should be covered in #13541
- [x] [class-based helper is torn down](https://github.com/emberjs/ember.js/blob/714b3d73d0e0f05d1c5a47def21c568686428ba3/packages/ember-glimmer/tests/integration/helpers/custom-helper-test.js#L347)
- [x] [class-based helper used in subexpression is destroyed](https://github.com/emberjs/ember.js/blob/714b3d73d0e0f05d1c5a47def21c568686428ba3/packages/ember-glimmer/tests/integration/helpers/custom-helper-test.js#L463)
- [x] [it should target the proper component when `action` is in yielded block](https://github.com/emberjs/ember.js/blob/d151ef178703d4c2d4d5d711908d73146897218c/packages/ember-glimmer/tests/integration/helpers/element-action-test.js#L1386) :lock: @chadhietala
- [x] [`{{input}}` tests](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/tests/integration/helpers/input-test.js#L68) Should be resolved in #13615
- [x] [should property escape unsafe hrefs](https://github.com/emberjs/ember.js/blob/3cfc9614bbd92ee8e80b6c4894b024f2e14bffae/packages/ember-glimmer/tests/integration/helpers/unbound-test.js#L98) :lock: @zackthehuman
- [x] [input placeholder attribute](https://github.com/emberjs/ember.js/blob/2dc2a19fd298b662de712593f242293a0bc0874c/packages/ember-glimmer/tests/integration/input-test.js#L44) This is properties vs attributes
- [x] [input maxlength attribute](https://github.com/emberjs/ember.js/blob/2dc2a19fd298b662de712593f242293a0bc0874c/packages/ember-glimmer/tests/integration/input-test.js#L52) This is properties vs attributes
- [x] [cursor position is not lost when updating content](https://github.com/emberjs/ember.js/blob/2dc2a19fd298b662de712593f242293a0bc0874c/packages/ember-glimmer/tests/integration/input-test.js#L64) @mmun may need to look
- [x] [Mutable bindings integration tests](https://github.com/emberjs/ember.js/blob/ee55672f4fb23055d792f1a2e2a2f1f68a36318d/packages/ember-glimmer/tests/integration/mutable-binding-test.js#L8) Should be addressed in #13541
- [x] [SVG element tests](https://github.com/emberjs/ember.js/blob/fa9866bf71aa5ef00ff661d0cbe4b0e2cf2ac554/packages/ember-glimmer/tests/integration/svg-test.js#L5) :lock: @chadhietala #13812
- [x] [Syntax test: {{#each-in}}](https://github.com/emberjs/ember.js/blob/b418b95ea3d31e3a3656906e6ad784422f648c31/packages/ember-glimmer/tests/integration/syntax/each-in-test.js#L41)
- [x] [{{each}} it can render duplicate primitive items](https://github.com/emberjs/ember.js/blob/da56d7a0b75caad63c8326fb070f5a32f5c7fd52/packages/ember-glimmer/tests/integration/syntax/each-test.js#L232)
- [x] [{{each}} it can render duplicate objects](https://github.com/emberjs/ember.js/blob/da56d7a0b75caad63c8326fb070f5a32f5c7fd52/packages/ember-glimmer/tests/integration/syntax/each-test.js#L254)
- [x] [{{each}} it maintains DOM stability for stable keys when list is updated](https://github.com/emberjs/ember.js/blob/da56d7a0b75caad63c8326fb070f5a32f5c7fd52/packages/ember-glimmer/tests/integration/syntax/each-test.js#L305) :lock: @fivetanley #13721
- [x] [{{unbound}} it does not update when the unbound helper is used](https://github.com/emberjs/ember.js/blob/78cea046e4ca01a068ae5701cd835357584327ff/packages/ember-glimmer/tests/utils/shared-conditional-tests.js#L554) :lock: @fivetanley #13717
- [x] Attributes are not going through a normalizing append. Failing test [can set dynamic style with -html-safe](https://github.com/emberjs/ember.js/blob/99096ec022923ae6b73a270417888010b2bce207/packages/ember-glimmer/tests/integration/content-test.js#L988)

__`{{render}}` test failures__
- [x] [Can this.render({into:...}) the render helper](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3545)
- [x] [Can disconnect from the render helper](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3572)
- [x] [Can this.render({into:...}) the render helper's children](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3597)
- [x] [Can disconnect from the render helper's children](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3626)
- [x] [Can this.render({into:...}) nested render helpers](https://github.com/emberjs/ember.js/blob/93a9aef89f1929dee5b07e38053b35bd420fbf08/packages/ember/tests/routing/basic_test.js#L3653)

__Cruff that can be removed?__
- [x] [should not affect rendering if rerender is called before initial render happens](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-views/tests/views/view/view_lifecycle_test.js#L38) Seem to be testing view lifecycle
- [x] [should not affect rendering if destroyElement is called before initial render happens](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-views/tests/views/view/view_lifecycle_test.js#L51)
- [x] [should replace DOM representation if rerender() is called after element is created](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-views/tests/views/view/view_lifecycle_test.js#L161)
- [x] [rerender of top level view during rendering should throw](https://github.com/emberjs/ember.js/blob/d5c6b68c0e3c4bb403ced65e360ad1d417a6bff2/packages/ember-views/tests/views/view/view_lifecycle_test.js#L74)
- [x] [component should receive the viewRegistry from the parentView](https://github.com/emberjs/ember.js/blob/0f2d9e6caa472b9bfbcafce220e85ebd4d4efc05/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L1921) #13505

## Real world applications
- [x] Ensure ember-twiddle works
- [x] Simple apps work
- [ ] Ember inspector
- [ ] Get a production app running
- [ ] Deploy an app to production to do a sanity check
- [ ] Remove the glimmer flag on master

## Unspecified Behavior

The following are tests that are failing and will back port if we find out this is a widely used use case, however the semantics here are just wrong.

- [get helper value should be updatable using {{input}} and (mut) - dynamic key](https://github.com/emberjs/ember.js/blob/38a1da1e59f2e7cb75b4088a9f5f7f5de00c969d/packages/ember-glimmer/tests/integration/helpers/get-test.js#L364) Should be part of #13615 #13532
- [get helper value should be updatable using {{input}} and (mut) - dynamic nested key](https://github.com/emberjs/ember.js/blob/38a1da1e59f2e7cb75b4088a9f5f7f5de00c969d/packages/ember-glimmer/tests/integration/helpers/get-test.js#L406) Should be part of #13615 #13532
- [get helper value should be updatable using {{input}} and (mut) - static key](https://github.com/emberjs/ember.js/blob/38a1da1e59f2e7cb75b4088a9f5f7f5de00c969d/packages/ember-glimmer/tests/integration/helpers/get-test.js#L441) Should be part of #13615 #13532
- [helper form updates on parent re-render](https://github.com/emberjs/ember.js/blob/3cfc9614bbd92ee8e80b6c4894b024f2e14bffae/packages/ember-glimmer/tests/integration/helpers/unbound-test.js#L147) This functionality seems weird

**Comment by rwjblue** [comment]
Thanks for putting this together @chadhietala

**Comment by mmun** [comment]
I'll take a stab at `{{render}}`.

**Comment by rwjblue** [comment]
@mmun - I updated the description to mark it as 🔒 'ed.

**Comment by zackthehuman** [comment]
I'm working on a change in Glimmer to fix the following:
 - should property escape unsafe hrefs
 - blacklists href bindings based on protocol

See https://github.com/tildeio/glimmer/pull/197 for more info.

**Comment by zackthehuman** [comment]
I'm working on fixing array iteration. PR here: https://github.com/emberjs/ember.js/pull/13763

Related tests:

- {{each}} it can render duplicate primitive items
- {{each}} it can render duplicate objects

**Comment by rwjblue** [comment]
I believe this is taken care of, closing...
