### ISSUE TITLE
Glimmer Component Manager TODO

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#15473]
Getting the Glimmer Component Manager to run with Ember means we must clean up a few things:

* [ ] Ember's env always uses a `CurlyComponentDefinition` instead of deferring to the manager for a definition. [In Ember](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/environment.js#L92), [Glimmer application does it correctly](https://github.com/glimmerjs/glimmer-application/blob/20bae09f5d814a783c479bff76e1eb7095bbd9d7/src/environment.ts#L140).
* [x] Allow glimmer `Environment` to be subclassed. https://github.com/emberjs/ember.js/pull/15472
* [x] Update Ember to be on Glimmer master.
* [x] Permit `{{@var}}` in template. [In Ember](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/assert-reserved-named-arguments.js#L12). Why you gotta be like that?

**Comment by rwjblue** [comment]
This has been superceded by the glimmer components RFC which is in the works...
