### ISSUE TITLE
[RFC 236] Ember.String Deprecation for @ember/string

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#15624]
# MIGRATED TO https://github.com/emberjs/rfc-tracking/issues/26

This is a meta-issue to track the implementation of https://github.com/emberjs/rfcs/blob/master/text/0236-deprecation-ember-string.md.

- ember.js
  - [ ] [deprecate Ember.String](https://github.com/emberjs/ember.js/pull/15739)
  - [x] [move htmlSafe and isHTMLSafe](https://github.com/emberjs/ember.js/pull/15626)
- ember-string -> `@ember/string`
  - [x] https://github.com/emberjs/ember-string/pull/1
- ember-string-prototype-extensions
  - [ ] https://github.com/locks/ember-string-prototype-extensions/pull/1
- ember-cli-babel
  - [x] [blacklist `@ember/string` if present](https://github.com/babel/ember-cli-babel/pull/176)
- [x] [babel-plugin-ember-modules-api-polyfill](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill)
- ember-rfc176-data
  - [x] [Move `htmlSafe` and `isHTMLSafe` to `@ember/template`](https://github.com/ember-cli/ember-rfc176-data/pull/38)
- website
  - [ ] [Deprecation guide](https://github.com/emberjs/website/pull/2995)

**Comment by Serabe** [comment]
@locks PTAL at https://github.com/ember-cli/ember-rfc176-data/pull/36 for the last part.

**Comment by Serabe** [comment]
Another one https://github.com/ember-cli/ember-rfc176-data/pull/38

**Comment by Serabe** [comment]
I've rebased everything except https://github.com/locks/ember-string-prototype-extensions/pull/1 and https://github.com/emberjs/website/pull/2995.

**Comment by pixelhandler** [comment]
@Serabe @locks This has been inactive for some time, is this up to date? what remains todo?

**Comment by Serabe** [comment]
AFAIK, everything. I closed my PR because I was rebasing it for over six months. Don't know if core is still interested on deprecating String prototype extensions.

**Comment by locks** [comment]
I am back to being more active again, I'm aiming to tackle this before year end.
