### ISSUE TITLE
Ember 3.0 Related Cleanup

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#15876]
- [x] Remove `phantomjs` usage from CI (tracking in https://github.com/emberjs/ember.js/pull/15877)
- [x] Remove IE9 and IE10 from CI runs. (tracking in https://github.com/emberjs/ember.js/pull/15879)
- [x] Leverage native WeakMaps :lock: @sivakumar-kailasam https://github.com/emberjs/ember.js/pull/15878
  - Remove `packages/ember-utils/lib/weak-map-utils.js`
  - Remove non-WeakMap fallback in `packages/ember-metal/lib/meta.js` [here](https://github.com/emberjs/ember.js/blob/fbc5d562487d6c10568cc9d3c04bcc507ce3c0d0/packages/ember-metal/lib/meta.js#L466-L496)
  - Remove non-WeakMap fallbacks in `packages/ember-metal/lib/transaction.js`
  - Remove non-WeakMap fallback in `packages/ember-glimmer/lib/utils/references.ts` [here](https://github.com/emberjs/ember.js/blob/fbc5d562487d6c10568cc9d3c04bcc507ce3c0d0/packages/ember-glimmer/lib/utils/references.ts#L53)
  - Remove `packages/ember-metal/lib/weak_map.js`
- [ ] Remove custom `Map` from `packages/ember-metal/lib/map.js` (being tracked in https://github.com/emberjs/ember.js/issues/13815) :lock: @maxwerr
- [x] Remove `console` polyfills / shims in `packages/ember-console/lib/index.js` https://github.com/emberjs/ember.js/pull/15881
- [x] `phantomjs` support / hacks https://github.com/emberjs/ember.js/pull/15880
  - [x] Remove `isPhantom` flag from `packages/ember-environment/lib/index.js`
  - [x] Remove workarounds for phantoms broken define property in `packages/ember-metal/lib/properties.js` ([here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-metal/lib/properties.js#L24-L39), [here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-metal/lib/properties.js#L225-L229), and [here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-metal/lib/properties.js#L183-L185))
- [ ] Deprecations labeled `until: '3.0.0'` - These need to be extracted (when possible) and behind an ENV flag when extraction is not possible. We will enable usage of these deprecated features through Ember 3.4 when using the 3.0 legacy addon. :lock: @thoov while we setup the legacy addon infrastructure...
  - [x]  (:lock: @thoov) `didInitAttrs` ([here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-views/lib/mixins/view_support.js#L432-L440), [here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-metal/lib/events.js#L43-L51), and [here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-views/lib/mixins/view_support.js#L73))
  - [x] `Ember.observer(callback, 'dependent-key1', 'dependent-key2')` [here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-metal/lib/mixin.js#L762-L768) (being worked on in https://github.com/emberjs/ember.js/pull/15893)
  - [x] `this.resource` in `Router.map` DSL [here](https://github.com/emberjs/ember.js/blob/a92a7cd003f7202a397aef2bbe95397ffe483034/packages/ember-routing/lib/system/dsl.js#L69-L78) (tracking in https://github.com/emberjs/ember.js/pull/15883)
  - [x] `fooBinding` support
    - `packages/ember-metal/lib/binding.js`
    - `packages/ember-template-compiler/lib/plugins/transform-old-binding-syntax.js`
    - `packages/ember-metal/lib/mixin.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-metal/lib/mixin.js#L260-L291) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-metal/lib/mixin.js#L372-L374)
    - `packages/ember-runtime/lib/system/core_object.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/system/core_object.js#L108-L111) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/system/core_object.js#L158)
    - `packages/ember-metal/lib/meta.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-metal/lib/meta.js#L53) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-metal/lib/meta.js#L365-L398)
  - [x] (🔒 @gowthamrm) Providing `resolver` as a function to the registry. [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/container/lib/registry.js#L605-L613) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/container/lib/registry.js#L27-L30)
  - [x] `immediateObserver` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-metal/lib/mixin.js#L787-L826) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/ext/function.js#L134-L167) (being worked on in https://github.com/emberjs/ember.js/pull/15894)
  - [x] `Enumerable#contains` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/mixins/enumerable.js#L210-L239) (being addressed in https://github.com/emberjs/ember.js/pull/15889)
  - [x] (:lock: @bekzod) Transforming `{{input on="enter" action="foo"}}` to `{{input enter="foo"}}` in `packages/ember-template-compiler/lib/plugins/transform-input-on-to-onEvent.js`, also [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-views/lib/mixins/text_support.js#L145-L172) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-views/lib/mixins/text_support.js#L341-L346)
  - [x] `EMBER_GLIMMER_ALLOW_BACKTRACKING_RERENDER` feature flag (this can be removed without flagging/guarding as it was never enabled) (tracking in https://github.com/emberjs/ember.js/pull/15890)
  - [x] `link-to`'s `currentWhen` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-glimmer/lib/components/link-to.ts#L353-L358) (being addressed in https://github.com/emberjs/ember.js/pull/15885)
  - [x] `Ember.String.fmt` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/system/string.js#L72-L80) :lock:ed by @locks (tracking in https://github.com/emberjs/ember.js/pull/15882)
  - [x] models wrapped in controllers for `link-to` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-glimmer/lib/components/link-to.ts#L784-L793) (being addressed by https://github.com/emberjs/ember.js/pull/15897/)
  - [x]  (:lock: @thoov) `_actions`
    - `packages/ember-runtime/lib/mixins/action_handler.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/mixins/action_handler.js#L233-L249)
    - `packages/ember-routing/lib/system/route.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-routing/lib/system/route.js#L2203)
    - `packages/ember-runtime/lib/controllers/controller.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/controllers/controller.js#L19)
    - `packages/ember-views/lib/views/core_view.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-views/lib/views/core_view.js#L82)
    - `packages/ember-runtime/lib/index.js` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/index.js#L33)
  - [x]  (:lock: @thoov) Legacy controller proxying behaviors (can be removed completely, `until` was incorrect) [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/mixins/-proxy.js#L108-L112) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/mixins/-proxy.js#L130-L134) 
  - [x] `Ember.Freezable` `packages/ember-runtime/lib/mixins/freezable.js` and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/mixins/copyable.js#L42-L69) (being addressed in https://github.com/emberjs/ember.js/pull/15891)
  - [x]  (:lock: @thoov) `{{render`
    - `{{render 'foo' someArg}}` - `packages/ember-template-compiler/lib/plugins/deprecate-render-model.js`
    - `{{render 'foo'}}` - `packages/ember-template-compiler/lib/plugins/deprecate-render.js`
    - Render component manager - `packages/ember-glimmer/lib/component-managers/render.ts`
    - `{{render` syntax - `packages/ember-glimmer/lib/syntax/render.ts` and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-glimmer/lib/syntax.ts#L68)
  - [x] `Ember.REQUIRED` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-metal/lib/mixin.js#L672-L690) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/system/core_object.js#L551-L554) (being addressed by https://github.com/emberjs/ember.js/pull/15892)
  - [x] `{Application,Engine,ApplicationInstance}.registry` support [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-runtime/lib/mixins/registry_proxy.js#L247-L282), [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-application/lib/system/application.js#L981-L988), and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-application/lib/system/application-instance.js#L490-L497)
  - [x] Arity check for initializers [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-application/lib/system/engine.js#L127-L136) (being addressed in https://github.com/emberjs/ember.js/pull/15886)
  - [ ] Orphaned outlets [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-routing/lib/system/router.js#L1494-L1512), [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-routing/lib/system/router.js#L1522-L1538), and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-glimmer/lib/views/outlet.ts#L34-L68)
  - [x] `Ember.Component#defaultLayout` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-glimmer/lib/component.ts#L574-L590) (addressed in https://github.com/emberjs/ember.js/pull/15896)
  - [x] `Ember.Handlebars.SafeString` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-glimmer/lib/utils/string.ts#L23-L36) and [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember/lib/index.js#L492-L495) (addressed in https://github.com/emberjs/ember.js/pull/15901)
  - [x] `Ember.deprecate` signature - [these](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-debug/lib/deprecate.js#L162-L196) deprecations should be changed to assertions (addressed by https://github.com/emberjs/ember.js/pull/15903)
  - [x]  `Ember.warn` signature - [these](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember-debug/lib/warn.js#L87-L109) deprecations should be changed to assertions https://github.com/emberjs/ember.js/pull/15900
  - [x] `Ember.K` [here](https://github.com/emberjs/ember.js/blob/78e0b6615e951029b587a0108ce7d277f26acaec/packages/ember/lib/index.js#L228-L253)

---

To pick up one of these items, please comment below and we'll update the checklist with `:lock: @your-name-here`...

**Comment by sivakumar-kailasam** [comment]
@rwjblue Should `Ember.WeakMap` be removed too?

**Comment by rwjblue** [comment]
> @rwjblue Should Ember.WeakMap be removed too?

I believe it is on the list above, under `Remove 'packages/ember-metal/lib/weak_map.js'`

**Comment by thoov** [comment]
If they haven't been taken I can start off with working on the `Leverage native WeakMaps` and all of the sub tasks for this

**Comment by rwjblue** [comment]
@thoov - Some are being tackled by @sivakumar-kailasam in https://github.com/emberjs/ember.js/pull/15878, can you take a look at that PR to help review (and determine what I've missed...)?

**Comment by thoov** [comment]
@rwjblue Will help with the review of that. I will change up my tactic and take the bottom 4 off of the list then.

**Comment by rwjblue** [comment]
@thoov  - Sounds good!  I have updated the items and marked the whole `Deprecations` subsection as :lock:ed, because we will need to create the legacy support addon and ENV flag infrastructure (so any one else working on deprecations will be blocked anyways).

**Comment by t-sauer** [comment]
I'd like to work on '`phantomjs` support / hacks' if that is still up for grabs

**Comment by sivakumar-kailasam** [comment]
@t-sauer I'm ready to raise a PR for that 😅

**Comment by t-sauer** [comment]
Well then I'll pick "Remove `console` polyfills / shims in `packages/ember-console/lib/index.js`" 🤞

**Comment by maxwerr** [comment]
Ill take a stab at `Remove custom Map from packages/ember-metal/lib/map.js`

**Comment by locks** [comment]
Taking `Ember.String.fmt`: https://github.com/emberjs/ember.js/pull/15882.

**Comment by locks** [comment]
Taking `this.resource` on RouterDSL: https://github.com/emberjs/ember.js/pull/15883.

**Comment by locks** [comment]
Taking `link-to`'s `currentWhen`: https://github.com/emberjs/ember.js/pull/15884.

**Comment by locks** [comment]
Taking "Arity check for initializers": https://github.com/emberjs/ember.js/pull/15886.

**Comment by rwjblue** [comment]
@locks one thing to keep in mind, is that we can't remove the functionality completely just yet.  We have to either add it to https://github.com/emberjs/ember-2-legacy or wrap it in a conditional flag. 

This is due to our stated goal from the 3.0 blog post:

> To further expand the migration window for 2.x applications to adopt 3.x, we will be releasing an addon that provides support for Ember.js 2.x APIs into the 3.x series. We’re committing to support that addon until Ember 3.4 (the first LTS candidate of the Ember 3.x cycle). If you want to contribute to this effort, you can find this package under the name ember-2-legacy.

**Comment by locks** [comment]
@rwjblue roger that 👍 I will review per-feature what the best approach might be. I'm partial to moving the implementation to the legacy addon if possible, if nothing else it seems neater.

**Comment by rwjblue** [comment]
Absolutely agreed!  We just need to ensure we have a path forward.  Things like `fooBinding` support will almost certainly have to be wrapped in conditionals here. But things like `Ember.String.fmt` and `link-to` `currentWhen` can totally be done in the addon itself directly.

**Comment by cibernox** [comment]
> Enumerable#contains 
https://github.com/emberjs/ember.js/pull/15889

**Comment by bekzod** [comment]
Taking `Ember.Freezable`

**Comment by bekzod** [comment]
Taking `Ember.REQUIRED`

**Comment by bekzod** [comment]
Taking `Ember.observer(callback, 'dependent-key1', 'dependent-key2')` #15893

**Comment by bekzod** [comment]
Taking `immediateObserver` #15894

**Comment by thoov** [comment]
@rwjblue Lock me up on:

`Ember.Component#defaultLayout`
`_actions`
`render`
`Legacy controller proxying behaviors`
`didInit`

**Comment by rwjblue** [comment]
@thoov - Done (but `defaultLayout` was already taken by @romulomachado in #15896)

**Comment by rwjblue** [comment]
I believe I have everything triaged, please ping me (probably in #dev-ember in slack) if I've missed something...

**Comment by bekzod** [comment]
Taking `Transforming {{input on="enter" action="foo"}} to {{input enter="foo"}}`

**Comment by cibernox** [comment]
Is there anything not claimed? It seems that `fooBinding` is free

**Comment by cibernox** [comment]
I take `{Application,Engine,ApplicationInstance}.registry`

**Comment by gowthamrm** [comment]
Taking `Providing resolver as a function to the registry`

**Comment by lorcan** [comment]
I can try to take `Orphaned outlets here, here, and here`

**Comment by alexander-alvarez** [comment]
@rwjblue we need to update the testing blueprints... not sure if this is explicitly 3.0 related

**Comment by rwjblue** [comment]
@alexander-alvarez - You are absolutely right!  I will try to get another quest issue together for the blueprints in the next day or so...
