### ISSUE TITLE
QUnit Blueprints Quest Issue

### ISSUE THREAD

**Issue by alexander-alvarez** [emberjs/ember.js#15933]
__Background__
We need to implement changes in blueprints and docs realted to [RFC 232] and [RFC 268].
(Some background for those unfamiliar http://rwjblue.com/2017/10/23/ember-qunit-simplication/)

As of `ember-cli-qunit@^4.1.1` (which is in the default blueprint as of `ember-cli@2.17`), we can implement the "Simplified QUnit" style tests in all tests except for acceptance tests.
In a future release of `ember-qunit` (likely 3.2.x), we will be able to leverage the implementation of `setupApplicationTest` from [RFC 268] for use in acceptance-tests. Once these changes are implemented upstream, we must implement the blueprint updates.
Currently, we have no way to generate these test files but we can run the [`ember-qunit-codemod`] to migrate test files and continue to iterate on the final output in the blueprint specific pull requests.

The desired behavior when generating testing blueprints is to, generate "Simplified QUnit" style tests if supported by the host app. We have several tasks below to extend the blueprints to support the "Simplified QUnit" style blueprints alongside the legacy, and ember-mocha blueprints. We can likely add to the behavior of [`test-framework-detector.js`] to support this other extension. Once these changes are completed we also need to update the guides to be consistent with the current `ember-cli` codebase. We should work with @rwjblue and the learning team (cc @locks) to determine how we best teach this.

__Tasks__
- [x] (🔒 @Turbo87) Extend  [`test-framework-detector.js`] to support a directory called `qunit-rfc-232-files` which will be where the "Simplified QUnit" blueprints will live in each of the blueprint test folders (e.g `blueprints/component-test/qunit-rfc-232-files/`). The decision to use the `qunit-rfc-232-files` directory should be based on the host's `ember-cli-qunit`
- [x] Add `<type>-test` "simplified QUnit" blueprints
    - [x] acceptance-test -  https://github.com/emberjs/ember.js/issues/15999
    - [x] (🔒 @Turbo87) component-test
    - [x]  (🔒 @snewcomer) controller-test    
    - [x] (🔒 @snewcomer) helper-test
    - [x] (🔒 @snewcomer) initializer-test
    - [x] (🔒 @snewcomer) instance-initializer-test
    - [x] (🔒 @boyanyordanov) mixin-test
    - [x] (:lock: @rwwagner90) route-test
    - [x] (🔒 @boyanyordanov) service-test
    - [x] (🔒 @snewcomer) util-test
- [x] (🔒 @alexander-alvarez) Extract the above tests blueprints into a standalone polyfill addon https://github.com/alexander-alvarez/ember-qunit-nested-module-blueprints-polyfill so developers can access the new testing blueprints regardless of what version of `ember-cli` they are on (so long as they are running `ember-cli-qunit@^4.1.1`)
- [x] (:lock: @jessica-jordan) Update testing section in https://github.com/emberjs/guides to reflect new style (note this should land very close to when the changes above are implemented)

---
To pick up one of these items, please comment below and we'll update the checklist with `:lock: @your-name-here`...

[RFC 232]: https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md
[RFC 268]: https://github.com/emberjs/rfcs/blob/master/text/0268-acceptance-testing-refactor.md
[`test-framework-detector.js`]: https://github.com/emberjs/ember.js/blob/master/blueprints/test-framework-detector.js
[`ember-cli@2.17`]: https://github.com/ember-cli/ember-new-output/blob/v2.17.0/package.json#L29
[`ember-qunit-codemod`]: https://github.com/rwjblue/ember-qunit-codemod

**Comment by rwjblue** [comment]
Awesome, thanks for organizing this @alexander-alvarez!

**Comment by Turbo87** [comment]
@alexander-alvarez should we use `qunit` for the new API blueprints and something else instead of `qunit` for the old blueprints? this would seem more intuitive to me 🤔

**Comment by Turbo87** [comment]
also I'm wondering if we should do the implementation in https://github.com/alexander-alvarez/ember-qunit-nested-module-blueprints-polyfill first and once those are solid we can import them here

**Comment by rwjblue** [comment]
@Turbo87 - I'd prefer to land the "real" implementations first (so that the polyfill truly is a polyfill). If that turns out to be costly (or I'm too much of a blocker in landing PR's) we can swap to targeting the polyfill addon first...

**Comment by rwjblue** [comment]
OK, first implementation is done and landed (along with the test framework detector changes required to support the path forward).  The game is afoot!

**Comment by snewcomer** [comment]
Doing the `helper-test` right now.

**Comment by rwwagner90** [comment]
@rwjblue I'm always happy to work on blueprints. Want to assign a couple my way?

**Comment by Turbo87** [comment]
@rwwagner90 choose one and announce it here, so that others are not doing the same work too :)

**Comment by rwwagner90** [comment]
@Turbo87 I'm not picky, but I'll randomly choose `route-test`

**Comment by rwjblue** [comment]
Updated description:

* :lock: `route-test` for @rwwagner90 
* ✅ `helper-test` 
* ✅ `component-test`

**Comment by snewcomer** [comment]
Tackling controller && initializer && instance-initializer tests in separate PR's!

**Comment by christophermlne** [comment]
If there's anything left I could take one.

**Comment by alexander-alvarez** [comment]
@christophermlne mixin, service, and util are still up for grabs

**Comment by snewcomer** [comment]
Taking the utils.  @christophermlne lmk if you want to tackle that one or want to take on either service or mixin!

**Comment by boyanyordanov** [comment]
I will try to do mixin and if I manage I will look into service as well. 
I haven't contributed to ember yet so I don't know if I'll be in over my head.

**Comment by Turbo87** [comment]
> I haven't contributed to ember yet so I don't know if I'll be in over my head.

@boyanyordanov don't worry, we're here to help you if you have questions :)

**Comment by boyanyordanov** [comment]
I'll go ahead and add a PR for service-test too.

**Comment by christophermlne** [comment]
Looks like a lot happened while I was sleeping ;-) Let me know if there is still anything left to do.

**Comment by jessica-jordan** [comment]
I'd like to update the testing section in the guides for these changes

**Comment by alexander-alvarez** [comment]
Thanks @jessica-jordan  :smile:, it's all yours

**Comment by rwjblue** [comment]
@alexander-alvarez - All of the blueprints other than acceptance are done. You are probably good to go on extracting to the polyfill addon...

**Comment by alexander-alvarez** [comment]
I'll get around to it ASAP

**Comment by alexander-alvarez** [comment]
I have 8 branches to push up in the polyfill repo once I get online again :D

**Comment by alexander-alvarez** [comment]
@rwjblue  @Turbo87 https://github.com/alexander-alvarez/ember-qunit-nested-module-blueprints-polyfill/pulls ready for y'all

**Comment by rwjblue** [comment]
Looks good, I think all if the polyfill addon PRs are merged at this point. 

Now only think left is the acceptance-test blueprint which we can do once https://github.com/emberjs/ember-qunit/pull/302 is reviewed and released.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/issues/15999 implements the acceptance-test blueprint.

It also bumps the minimum version of ember-cli-qunit to 4.2.0.

**Comment by alexander-alvarez** [comment]
Released in https://github.com/alexander-alvarez/ember-qunit-nested-module-blueprints-polyfill/releases/tag/1.1.0

**Comment by rwjblue** [comment]
@locks / @jessica-jordan - Do y'all want to track the guides work here, or would it be better to make a guides specific issue for the remaining work item?

**Comment by jessica-jordan** [comment]
@rwjblue Personally, I'm happy to track it here, but I'm good with either solution

**Comment by rwjblue** [comment]
Thanks everyone for your hard work here!
