### ISSUE TITLE
[RFC 297] Deprecation Ember.Logger

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#16231]
RFC: https://github.com/emberjs/rfcs/pull/297

While the RFC is not merged yet, it was recently moved into Final Comment Period and there is general support for this to land, so we feel confident that work can commence in preparation.

## Tasks
- [x] Deprecate APIs in Ember.js - [PR](https://github.com/emberjs/ember.js/pull/16250)
- [ ] Develop and publish codemod
- Write Deprecation Guide
  - [x] emberjs/website - [PR](https://github.com/emberjs/website/pull/3197)
  - [x] ember-learn/deprecation-app - [PR](https://github.com/ember-learn/deprecation-app/pull/91)
- [x] Review API docs
- [x] Review Guides - [PR](https://github.com/emberjs/guides/pull/2230)
- Review top addons
  - [x] Ember Data - [PR](https://github.com/emberjs/data/pull/5356)
  - [x] ember-resolver - [PR](https://github.com/emberjs/ember.js/issues/16231)

**Comment by lupestro** [comment]
Locally, as of last weekend... 
* I currently have the two passing references to Ember.Logger out of the Guides. These could probably go into a pull request with or without the RFC.
* I have a draft entry for the Deprecation Guide written, but the final details will depend on release timing. 
* I've also coded the change for the Ember.Debug to not use Ember.Logger and I've coded the deprecation itself, although I think this may need to go back and wrap all of this in a feature flag.
* I've reworked tests that intercepted Ember.Logger to intercept console instead, but there are maybe four router tests that never set it back but exit after calling `bootApplication();` and do a run() of a transition or two, which concerns me a little. 
* All existing tests are passing, but, due to the issue with the router tests, I need to verify whether the test leakage to the browser console is identical before and after my change.
...I get busy elsewhere during the week. I'm hoping to have the deprecation itself completed, feature flag and all, this weekend, or before the RFC exits FCP.

I'm not sure of the most comprehensive way to review the API docs besides bulk searches on the source, which I've been doing anyway. I think I've done the right things in the code comments to properly mark the deprecation but have no idea how to build the API docs to see the final effect. 

That leaves the codemod and the review of the addons, for which I will need a little help.

**Comment by lupestro** [comment]
So far, we have the following PRs: 
guides - 2230 (a couple of Logger references - merged and closed already)
emberjs - 16250 (deprecation code)
data - 5356 (one reference to Logger)
website - 3197 (corresponding deprecation page)

**Comment by lupestro** [comment]
I encountered a couple of unexpected speed-bumps using console in Edge and IE11. The simple page in the attachment can be used to easily observe the console uses that pose a problem and their easy workarounds. Try it in Edge and IE11 with and without the developer tools up, then try it in other browsers. [tryconsole.zip](https://github.com/emberjs/ember.js/files/1735146/tryconsole.zip)

**Comment by lupestro** [comment]
Uh-oh. I just realized, walking emberobserver, that we didn’t have ember-resolver on the above list. So many projects...

**Comment by locks** [comment]
@lupestro not sure I understand?

**Comment by lupestro** [comment]
In wake of our discussion @locks, here’s the issue over on ember-resolver:
[https://github.com/ember-cli/ember-resolver/issues/223]()

**Comment by rwjblue** [comment]
Great job!!

**Comment by scottkidder** [comment]
Is there a codemod or any other discussion for this deprecation?

**Comment by lupestro** [comment]
There has been discussion for it. We captured prior discussion in [the RFC itself](https://github.com/emberjs/rfcs/blob/master/text/0297-deprecate-ember-logger.md), the [PR for the RFC](https://github.com/emberjs/rfcs/pull/297) carries further discussion, and the [deprecation text](https://emberjs.com/deprecations/v3.x#toc_ember-console-deprecate-logger) describes what needs to change, and what you have to do to deal with the one or two remaining oddities of console in IE11 and Edge. 

There is no codemod to automate changing the code, as the work can involve a little judgment, but the changes are generally very local and simple, as the deprecation text tries to show. The RFC references some of the code that we examined in determining the impact of the change. In all the code we looked at, it seemed straightforward to find and make any needed changes by hand.
