### ISSUE TITLE
META ISSUE: Routing fails to identify willBeActive for param-only changes.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#16275]
There are numerous issues reported on this topic. I'm going to fix them because I need it to work correctly.

Simplified reproduction as a Twiddle with instructions: https://ember-twiddle.com/52669dbb90a5f099cd6e78957e9fd892?openFiles=routes.products.details.js%2C&route=%2Fproducts%2F4

One piece of new information: it only fails for async transitions.

This is the line that triggers the bug:
https://github.com/tildeio/router.js/blame/17a4cd3b6ac8053f3eb20d4358e2bc37653774b6/lib/router/transition-intent/named-transition-intent.js#L121

This has been existing since *at least* 2.0.

Related:
- [ ] https://github.com/emberjs/ember.js/issues/12419
- [ ] https://github.com/emberjs/ember.js/issues/10989
- [ ] https://github.com/emberjs/ember.js/issues/10195
- [ ] https://github.com/tildeio/router.js/issues/236

/cc @topaxi @bgentry
