### ISSUE TITLE
Improve docs for the Router Service

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#16518]
The Router Service docs need a more beginner-friendly description. Right now it says:

> The Router service is the public API that provides component/view layer access to the router.

I recommend that the "main" description be a PR on its own. [This](https://github.com/emberjs/ember.js/blob/v3.1.0/packages/ember-routing/lib/services/router.js#L15) is the file that needs to change. 

Ideally the most commonly used APIs should have code blocks demonstrating their use and some explanations of their purpose or how to use them. For example, see [EmberArray](https://emberjs.com/api/ember/3.1/classes/EmberArray). Additional PRs could include a code block demonstrating the use of each method or property.

Maintainers may feel free to edit this issue directly. @locks can you mark this help-wanted/new contributors if it looks good to you?

- [ ] https://github.com/emberjs/ember.js/issues/16596

## Tasks
- Methods
  - isActive (@rscotchmer) (@pauljeannot) https://github.com/emberjs/ember.js/pull/18471
    - [ ] explanation
    - [ ] code sample
  - recognize
    - [x] explanation
    - [ ] code sample
  - recognizeAndLoad
    - [x] explanation
    - [ ] code sample
  - replaceWith (@teamdraftbox)
    - [x] explanation
    - [ ] code sample
  - transitionTo
    - [x] explanation
    - [ ] code sample
  - urlFor
    - [x] explanation
    - [x] code sample
- Properties
  - currentRoute (@sdebarros)
    - [ ] explanation (what's a `RouteInfo`?)
    - [ ] code sample (needs usage sample)
  - currentRouteName
    - [x] explanation
    - [ ] code sample (needs usage sample)
  - currentURL
    - [x] explanation
    - [ ] code sample (needs usage sample)
  - location
    - [ ] explanation (should link to different Location types)
    - [ ] code sample
  - rootURL
    - [x] explanation
    - [ ] code sample (needs usage sample)
- Events
  - routeDidChange
    - [x] explanation
    - [x] code sample
  - routeWillChange
    - [x] explanation
    - [x] code sample

**Comment by Parrryy** [comment]
I'd be happy to pick this up.

**Comment by Serap08** [comment]
Is this issue still open? if yes, I can contribute.

**Comment by amanriquez** [comment]
Looking for my first open source contribution, any help needed here?

**Comment by hakilebara** [comment]
#16858

**Comment by locks** [comment]
@amanriquez definitely! I have updated the original post with a list of what there is to document in `RouterService` and their current state.
Pick one item and I'll assign you to it :)

**Comment by PrimeN** [comment]
Looking to contribute to this project. I can take on a portion of this and update documentation/description.

**Comment by locks** [comment]
@PrimeN thanks for the help! Please comment with the item you wish to take so we can assign it to you :)

**Comment by rscotchmer** [comment]
Hello!  I'd like to contribute to the project by writing up an explanation and code sample for the isActive method.

**Comment by locks** [comment]
@rscotchmer thanks for the help! I'll tag you in the list.

**Comment by locks** [comment]
Hi @Serap08, @amanriquez and @PrimeN, can you pick one item from the task list so I can assign them to you? That way we avoid several people working on the same item!

**Comment by teamdraftbox** [comment]
hey @locks  im looking  to contribute to the above mentioned issue, this is my first time in contributing to a open source, i would like to work on **replaceWith method issue,** please let me know what exactly is the procedure so i can start working on it

**Comment by mschinis** [comment]
☝️ happy to take `transitionTo` here

**Comment by locks** [comment]
@Serap08 @amanriquez @PrimeN @mschinis poke poke :)

@teamdraftbox hi, thanks for your interest!
The way to start is:
1. comment on this thread which part you want to take on (done!)
2. fork the repository
3. create a branch with a name of your choosing, for example `git checkout -b router-replace-with`
4. open `ember.js/packages/@ember/-internals/routing/lib/services/router.ts`
5. add your documentation changes
6. `git commit` your changes
7. push the branch to your github fork
8. go to your fork on github.com, and you should see a banner telling you to create a new PR. click the create button
9. wait for our review!

If you need further help, reach out to `#dev-ember-learning` on the Discord server!

**Comment by teamdraftbox** [comment]
Hi,
Thanks for the instructions,will follow the above instructions

**Comment by madarsbiss** [comment]
i would love to contribute on this

**Comment by locks** [comment]
@madarsbiss have you picked a specific method/property so I can assign you?

**Comment by sdebarros** [comment]
✋ I'll take `currentRoute` for documenting.

**Comment by sdebarros** [comment]
✋ will be also working on the location property docs

**Comment by pauljeannot** [comment]
🤚 Took the nice work done by @rscotchmer, and updated it with new class syntax, for the isActive method.

**Comment by esbanarango** [comment]
Can I take `transitionTo` code sample? ✋

**Comment by locks** [comment]
@esbanarango hi :) have you sent a PR yet?

**Comment by esbanarango** [comment]
@locks looks like the code sample was already added here: https://github.com/emberjs/ember.js/pull/18179 We could update the description of this issue. Check code samples for _transitionTo_, _replaceWith_ and _recognize_.

**Comment by RVMac** [comment]
Hi, I'm looking to contribute (I'm a beginner BTW). Any task needed to be done?

**Comment by locks** [comment]
Thank you everyone for your help! I believe we have done enough work to close this issue :)
