### ISSUE TITLE
Migrate internals to public modules API.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#16529]
This is a tracking issue for migrating the internal repo into the public JS modules API. 

- [x] `@ember/application`
  - [x] `Ember.Application` -> `default`
  - [x] `Ember.onLoad` -> `onLoad`
  - [x] `Ember.runLoadHooks` -> `runLoadHooks`
  - [x] `Ember.getOwner` -> `getOwner`
  - [x] `Ember.setOwner` -> `setOwner`
- [x] `@ember/application/instance`
  - [x] `Ember.ApplicationInstance` -> `default`
- [x] `@ember/engine`
  - [x] `Ember.Engine` -> `default`
  - [x] `Ember.getEngineParent` -> `getEngineParent`
- [x] `@ember/engine/instance`
  - [x] `Ember.EngineInstance` -> `default`
- [x] `@ember/error`
  - [x] `Ember.Error` -> `default`
- [ ] `@ember/application/deprecations`
  - [ ] `Ember.deprecate` -> `deprecate`
  - [ ] `Ember.deprecateFunc` -> `deprecateFunc`
- [x] `@ember/controller`
  - [x] `Ember.Controller` -> `default`
  - [x] `Ember.inject.controller` -> `inject`
- [ ] `@ember/array`
  - [ ] `Ember.Array` -> `default`
  - [ ] `Ember.A` -> `A`
  - [ ] `Ember.isArray` -> `isArray`
  - [ ] `Ember.makeArray` -> `makeArray`
- [ ] `@ember/array/mutable`
  - [ ] `Ember.MutableArray` -> `default`
- [ ] `@ember/array/proxy`
  - [ ] `Ember.ArrayProxy` -> `default`
- [ ] `@ember/object/core`
  - [ ] `Ember.CoreObject` -> `default`
- [ ] `@ember/object`
  - [ ] `Ember.Object` -> `default`
  - [ ] `Ember.defineProperty` -> `defineProperty`
  - [ ] `Ember.get` -> `get`
  - [ ] `Ember.set` -> `set`
  - [ ] `Ember.getProperties` -> `getProperties`
  - [ ] `Ember.setProperties` -> `setProperties`
  - [ ] `Ember.getWithDefault` -> `getWithDefault`
  - [ ] `Ember.observer` -> `observer`
  - [ ] `Ember.computed` -> `computed`
  - [ ] `Ember.trySet` -> `trySet`
  - [ ] `Ember.aliasMethod` -> `aliasMethod`
- [ ] `@ember/object/computed`
  - [ ] `Ember.ComputedProperty` -> `default`
  - [ ] `Ember.expandProperties` -> `expandProperties`
  - [x] `Ember.computed.empty` -> `empty`
  - [x] `Ember.computed.notEmpty` -> `notEmpty`
  - [x] `Ember.computed.none` -> `none`
  - [x] `Ember.computed.not` -> `not`
  - [x] `Ember.computed.bool` -> `bool`
  - [x] `Ember.computed.match` -> `match`
  - [x] `Ember.computed.equal` -> `equal`
  - [x] `Ember.computed.gt` -> `gt`
  - [x] `Ember.computed.gte` -> `gte`
  - [x] `Ember.computed.lt` -> `lt`
  - [x] `Ember.computed.lte` -> `lte`
  - [x] `Ember.computed.alias` -> `alias`
  - [x] `Ember.computed.oneWay` -> `oneWay`
  - [x] `Ember.computed.reads` -> `reads`
  - [x] `Ember.computed.readOnly` -> `readOnly`
  - [x] `Ember.computed.deprecatingAlias` -> `deprecatingAlias`
  - [x] `Ember.computed.and` -> `and`
  - [x] `Ember.computed.or` -> `or`
  - [x] `Ember.computed.collect` -> `collect`
  - [x] `Ember.computed.sum` -> `sum`
  - [x] `Ember.computed.min` -> `min`
  - [x] `Ember.computed.max` -> `max`
  - [x] `Ember.computed.map` -> `map`
  - [x] `Ember.computed.sort` -> `sort`
  - [x] `Ember.computed.setDiff` -> `setDiff`
  - [x] `Ember.computed.mapBy` -> `mapBy`
  - [x] `Ember.computed.mapProperty` -> `mapProperty`
  - [x] `Ember.computed.filter` -> `filter`
  - [x] `Ember.computed.filterBy` -> `filterBy`
  - [x] `Ember.computed.filterProperty` -> `filterProperty`
  - [x] `Ember.computed.uniq` -> `uniq`
  - [x] `Ember.computed.uniqBy` -> `uniqBy`
  - [x] `Ember.computed.union` -> `union`
  - [x] `Ember.computed.intersect` -> `intersect`
- [ ] `@ember/object/evented`
  - [ ] `Ember.Evented` -> `default`
  - [ ] `Ember.on` -> `on`
- [ ] `@ember/object/events`
  - [ ] `Ember.addListener` -> `addListener`
  - [ ] `Ember.removeListener` -> `removeListener`
  - [ ] `Ember.sendEvent` -> `sendEvent`
- [ ] `@ember/object/mixin`
  - [ ] `Ember.Mixin` -> `default`
- [ ] `@ember/object/proxy`
  - [ ] `Ember.ObjectProxy` -> `default`
- [ ] `@ember/object/promise-proxy-mixin`
  - [ ] `Ember.PromiseProxyMixin` -> `default`
- [ ] `@ember/object/observers`
  - [ ] `Ember.addObserver` -> `addObserver`
  - [ ] `Ember.removeObserver` -> `removeObserver`
- [ ] `@ember/object/observable`
  - [ ] `Ember.Observable` -> `default`
- [ ] `@ember/object/internals`
  - [ ] `Ember.copy` -> `copy`
  - [ ] `Ember.guidFor` -> `guidFor`
  - [ ] `Ember.cacheFor` -> `cacheFor`
- [ ] `@ember/component`
  - [ ] `Ember.Component` -> `default`
- [ ] `@ember/component/checkbox`
  - [ ] `Ember.Checkbox` -> `default`
- [ ] `@ember/component/text-area`
  - [ ] `Ember.TextArea` -> `default`
- [ ] `@ember/component/text-field`
  - [ ] `Ember.TextField` -> `default`
- [ ] `@ember/debug`
  - [x] `Ember.debug` -> `debug`
  - [ ] `Ember.inspect` -> `inspect`
  - [x] `Ember.runInDebug` -> `runInDebug`
  - [x] `Ember.warn` -> `warn`
  - [x] `Ember.assert` -> `assert`
  - [x] `Ember.Debug.registerDeprecationHandler` -> `registerDeprecationHandler`
  - [x] `Ember.Debug.registerWarnHandler` -> `registerWarnHandler`
- [ ] `@ember/debug/container-debug-adapter`
  - [ ] `Ember.ContainerDebugAdapter` -> `default`
- [ ] `@ember/debug/data-adapter`
  - [ ] `Ember.DataAdapter` -> `default`
- [ ] `@ember/application/resolver`
  - [ ] `Ember.Resolver` -> `default`
- [x] `@ember/application/globals-resolver`
  - [x] `Ember.DefaultResolver` -> `default`
- [ ] `@ember/component/helper`
  - [ ] `Ember.Helper` -> `default`
  - [ ] `Ember.Helper.helper` -> `helper`
- [x] `@ember/instrumentation`
  - [x] `Ember.Instrumentation.instrument` -> `instrument`
  - [x] `Ember.Instrumentation.reset` -> `reset`
  - [x] `Ember.Instrumentation.subscribe` -> `subscribe`
  - [x] `Ember.Instrumentation.unsubscribe` -> `unsubscribe`
- [ ] `@ember/routing/location`
  - [ ] `Ember.Location` -> `default`
- [ ] `@ember/routing/auto-location`
  - [ ] `Ember.AutoLocation` -> `default`
- [ ] `@ember/routing/hash-location`
  - [ ] `Ember.HashLocation` -> `default`
- [ ] `@ember/routing/history-location`
  - [ ] `Ember.HistoryLocation` -> `default`
- [ ] `@ember/routing/none-location`
  - [ ] `Ember.NoneLocation` -> `default`
- [ ] `@ember/routing/link-component`
  - [ ] `Ember.LinkComponent` -> `default`
- [x] `@ember/map`
  - [x] `Ember.Map` -> `default`
- [x] `@ember/map/with-default`
  - [x] `Ember.MapWithDefault` -> `default`
- [ ] `@ember/enumerable`
  - [ ] `Ember.Enumerable` -> `default`
- [ ] `@ember/polyfills`
  - [x] `Ember.assign` -> `assign`
  - [x] `Ember.merge` -> `merge`
  - [x] `Ember.create` -> `create`
  - [x] `Ember.keys` -> `keys`
  - [ ] `Ember.platform.hasPropertyAccessors` -> `hasPropertyAccessors`
- [ ] `@ember/routing/route`
  - [ ] `Ember.Route` -> `default`
- [ ] `@ember/routing/router`
  - [ ] `Ember.Router` -> `default`
- [x] `@ember/runloop`
  - [x] `Ember.run` -> `run`
  - [x] `Ember.run.begin` -> `begin`
  - [x] `Ember.run.bind` -> `bind`
  - [x] `Ember.run.cancel` -> `cancel`
  - [x] `Ember.run.debounce` -> `debounce`
  - [x] `Ember.run.end` -> `end`
  - [x] `Ember.run.join` -> `join`
  - [x] `Ember.run.later` -> `later`
  - [x] `Ember.run.next` -> `next`
  - [x] `Ember.run.once` -> `once`
  - [x] `Ember.run.schedule` -> `schedule`
  - [x] `Ember.run.scheduleOnce` -> `scheduleOnce`
  - [x] `Ember.run.throttle` -> `throttle`
- [x] `@ember/service`
  - [x] `Ember.Service` -> `default`
  - [x] `Ember.inject.service` -> `inject`
- [ ] `@ember/string`
  - [x] `Ember.String.camelize` -> `camelize`
  - [x] `Ember.String.capitalize` -> `capitalize`
  - [x] `Ember.String.classify` -> `classify`
  - [x] `Ember.String.dasherize` -> `dasherize`
  - [x] `Ember.String.decamelize` -> `decamelize`
  - [x] `Ember.String.fmt` -> `fmt`
  - [ ] `Ember.String.htmlSafe` -> `htmlSafe`
  - [ ] `Ember.String.isHTMLSafe` -> `isHTMLSafe`
  - [x] `Ember.String.loc` -> `loc`
  - [x] `Ember.String.underscore` -> `underscore`
  - [x] `Ember.String.w` -> `w`
- [ ] `@ember/test/adapter`
  - [ ] `Ember.Test.Adapter` -> `default`
- [ ] `@ember/test`
  - [ ] `Ember.Test.registerAsyncHelper` -> `registerAsyncHelper`
  - [ ] `Ember.Test.registerHelper` -> `registerHelper`
  - [ ] `Ember.Test.registerWaiter` -> `registerWaiter`
  - [ ] `Ember.Test.unregisterHelper` -> `unregisterHelper`
  - [ ] `Ember.Test.unregisterWaiter` -> `unregisterWaiter`
- [ ] `@ember/utils`
  - [ ] `Ember.isBlank` -> `isBlank`
  - [ ] `Ember.isEmpty` -> `isEmpty`
  - [ ] `Ember.isEqual` -> `isEqual`
  - [ ] `Ember.isNone` -> `isNone`
  - [ ] `Ember.isPresent` -> `isPresent`
  - [ ] `Ember.tryInvoke` -> `tryInvoke`
  - [ ] `Ember.typeOf` -> `typeOf`
  - [ ] `Ember.compare` -> `compare`
- [ ] `jquery`
  - [ ] `Ember.$` -> `default`
- [x] `rsvp`
  - [x] `Ember.RSVP` -> `default`
  - [x] `Ember.RSVP.all` -> `all`
  - [x] `Ember.RSVP.allSettled` -> `allSettled`
  - [x] `Ember.RSVP.race` -> `race`
  - [x] `Ember.RSVP.hash` -> `hash`
  - [x] `Ember.RSVP.hashSettled` -> `hashSettled`
  - [x] `Ember.RSVP.defer` -> `defer`
  - [x] `Ember.RSVP.denodeify` -> `denodeify`
  - [x] `Ember.RSVP.on` -> `on`
  - [x] `Ember.RSVP.off` -> `off`
  - [x] `Ember.RSVP.resolve` -> `resolve`
  - [x] `Ember.RSVP.reject` -> `reject`
  - [x] `Ember.RSVP.map` -> `map`
  - [x] `Ember.RSVP.filter` -> `filter`
  - [x] `Ember.RSVP.Promise` -> `Promise`

---

At the moment, progress is 🔒'ed by @rwjblue, but at some future point this will be opened up as a call for help style quest issue...

**Comment by sandstrom** [comment]
@locks Maybe this issue can be closed? Or is it still relevant?

**Comment by locks** [comment]
Yeah, I guess so!
