### ISSUE TITLE
[Quest] Mocha Blueprints for RFCs 232/268

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#16863]
### Background
https://github.com/emberjs/ember.js/issues/15933 updated the blueprints for Qunit to reflect the changes made in RFC 232 and RFC 268. As of ember-mocha 0.14.0 we can implement these same blueprints for Mocha tests as well. 

The desired behavior when generating testing blueprints is to generate "Simplified Mocha" style tests if supported by the host app. We have several tasks below to extend the blueprints to support the "Simplified Mocha" style blueprints alongside the legacy, and ember-mocha blueprints.

### Tasks

 + [x]  https://github.com/emberjs/ember.js/pull/16865 (🔒 @dhaulagiri)  Extend [test-framework-detector.js](https://github.com/emberjs/ember.js/blob/master/blueprints/test-framework-detector.js) to support a directory called `mocha-rfc-232-files` which will be where the "Simplified Mocha" blueprints will live in each of the blueprint test folders (e.g `blueprints/component-test/mocha-rfc-232-files/`). The decision to use the `mocha-rfc-232-files` directory should be based on the host's `ember-mocha` version
 + [ ]  Add `<type>-test` "simplified Mocha" blueprints
   + [x] https://github.com/emberjs/ember.js/pull/16899 (🔒 @dhaulagiri) acceptance-test
   + [x]  https://github.com/emberjs/ember.js/pull/16865 (🔒 @dhaulagiri) component-test
   + [x] https://github.com/emberjs/ember.js/pull/16894 (🔒 @dhaulagiri) controller-test
   + [x]  https://github.com/emberjs/ember.js/pull/16896 (🔒 @dhaulagiri) helper-test
   + [ ]  initializer-test
   + [ ]  instance-initializer-test
   + [x]  https://github.com/emberjs/ember.js/pull/16914 (🔒 @dhaulagiri) mixin-test
   + [x]  https://github.com/emberjs/ember.js/pull/16897 (🔒 @dhaulagiri) route-test
   + [x]  https://github.com/emberjs/ember.js/pull/16913 (🔒 @dhaulagiri) service-test
   + [x] https://github.com/emberjs/ember.js/pull/16898 (🔒 @dhaulagiri) util-test

**Comment by rwjblue** [comment]
An ember-mocha with the newer APIs hadn’t landed at that point (the repo needed more work before it was ready). I think at this point the best path is to make a quest style issue with a checklist and guidance. Generally speaking these efforts move forward fairly quickly.

I personally would love to see updated blueprints land in time for 3.4 (current beta).

**Comment by Dhaulagiri** [comment]
@rwjblue I copied over the quest items from the qunit issue here to turn this into a quest for updating the mocha blueprints. Let me know if this plan seems sound (I'm a little out of the loop).

**Comment by shadi4778** [comment]
issue

**Comment by Dhaulagiri** [comment]
I'll probably need help with the initializer tests as they seem to differ from qunit in ways that I can't quite understand the "right" way to write them

**Comment by simonihmig** [comment]
> I'll probably need help with the initializer tests as they seem to differ from qunit in ways that I can't quite understand the "right" way to write them

I am interested in wrapping this up. @Dhaulagiri can you elaborate on this? How/why would the Mocha tests have to differ?

**Comment by Dhaulagiri** [comment]
@simonihmig i wish I had been more specific here, but if I recall correctly if I tried to mimic the same application test setup as the qunit tests I was running into unexpected errors in the mocha tests.

**Comment by simonihmig** [comment]
Here are two PRs for the missing (instance-) initializer blueprints: #17411, #17412

**Comment by simonihmig** [comment]
With the above two PRs being merged, the remaining points can be checked off and this issue closed! :tada:

**Comment by Dhaulagiri** [comment]
Thanks!!!
