### ISSUE TITLE
[QUEST] Native Classes

### ISSUE THREAD

**Issue by pzuraq** [emberjs/ember.js#16927]
## Background

This issue is for tracking the progress on Native Classes in Ember! The task list below is actively used by the strike team to keep track of all of the major tasks left before we can officially ship. Feel free to ask questions or help out!

Original RFC [here](https://github.com/emberjs/rfcs/blob/master/text/0240-es-classes.md).

## Tasks

- [x] ~Decide [Native Class Constructor Update RFC #337](https://github.com/emberjs/rfcs/pull/337)~

  ~This ultimately decides what the behavior of native classes, and the way we write them, looks like until EmberObject is deprecated and removed from the framework. We need to get a final decision on this RFC before we can move forward.~

  - [x] ~feature #16795~

- [x] Bugfixes

  We have some open issues that could cause compatibility issues when converting to native classes. We need to get these merged.

    - [x] ~ES6 classes on/removeListener and observes/removeObserver interop v2 #16923~
    - [x] ~[BUGFIX] Adds default implementations of Component lifecycle hooks #17169~ 

- [x] Polyfills
  
  Currently we're going to polyfill back to 3.4 (the last LTS). Polyfills for earlier versions are definitely welcome and we will be working on them as we have time, but help would be appreciated!

    - [ ] 2.16 #16806
    - [ ] 2.18 #16805
    - [x] 3.4 #17167
    - [x] 3.5 #17168

- [x] ~Write ReadOnly/Volatile Deprecation RFC~

  ~Clobberability is an anti-pattern, and volatile is generally not needed. This is not something that is 100% necessary to move forward, but it resolves differences between native getters/setters and computeds so ideally we can address it quickly.~

  [readOnly RFC](https://github.com/emberjs/rfcs/pull/369)
  [volatile RFC](https://github.com/emberjs/rfcs/pull/369)

- [x] Write Decorators RFC (once decorators reach stage 3)

  We can move forward with the codemod with decorators being an addon, but we should fold them into Ember as soon as we can. Stage 2 is potentially viable, but ideally we would wait until stage 3.

- [x] ~Address open issues on ember-decorators~
  - [x] ~[Add @computed.readOnly and @computed.volatile](https://github.com/ember-decorators/ember-decorators/issues/272)~

    ~We need a way to access these APIs for the codemod.~

  - [x] ~[ES6 blueprints not being used](https://github.com/ember-decorators/ember-decorators/issues/269)~

    ~General bug, this is important for shipping though since users will want to use these generators, and they can probably be ported into Ember.~

  - [x] ~[route queryParams support](https://github.com/ember-decorators/ember-decorators/issues/235)~

    ~I think this may need to be a class decorator, given the prototype placement of an object. Only one instance of said object will ever be created though, so maybe not an issue.~

  - [x] ~[Filter array based on another property?](https://github.com/ember-decorators/ember-decorators/issues/64)~

    ~Need a way to access `.property()` and add properties to computeds, for the codemod.~ This was ultimately unneeded

- [x] ~Update decorators~
  - [x] ~Update to Babel 7~
  - [x] ~Update decorators to use stage 2 transforms~ 

    Upon further discussion it seems like we'll be stuck on stage 1 transforms until Typescript updates, which will likely be stage 3

- [x] Finish up [codemod](https://github.com/scalvert/ember-es6-class-codemod/)
  - [x] Stage 2/3
  - [x] Folder globbing, types

- [ ] Update guides - Blocked on Decorators RFC

**Comment by efx** [comment]
@pzuraq nitpick: "volatile RFC" deprecation link should be https://github.com/emberjs/rfcs/pull/370

**Comment by locks** [comment]
Thanks for the help! Closing as finished.
