### ISSUE TITLE
Backport #17003 for 2.18 LTS

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#17006]
- [x] Land glimmerjs/glimmer-vm#854
- [ ] Release @glimmer/* 0.25.next
- [ ] Backport failing tests from #17003 to lts-2-18
- [ ] Bump @glimmer/* on lts-2-18

**Comment by chancancode** [comment]
The glimmer changes are done in https://github.com/glimmerjs/glimmer-vm/pull/854/, currently looking for reviewers.

**Comment by locks** [comment]
@chancancode this is dead? :x

**Comment by chancancode** [comment]
Probably too late now :P
