### ISSUE TITLE
[META] Routing Service "Go" Items

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#17027]
This is the tracking issue to "go" Router Service:

- [x] Implement `routeWillChange` and `routeDidChange` events #17025 
- [x] Implement `RouteInfo`s #17025
- [x] Deprecate `willTransition` and `didTransition` events #17025 
- [x] Implement `recognize` #17034
- [x] Implement `recognizeAndLoad` #17034
- [x] Implement `RouteInfoWithAttributes` type #17034 
- [x] Implement `currentRoute` #17041
- [x] Warn on touching `transition.state` and direct people to routing service #17038 
- [x] Warn on touching `transition.params` and direct people to routing service #17038
- [x] Write deprecation guide for HandlerInfo usage https://github.com/ember-learn/deprecation-app/pull/192
- [x] Write deprecation guide for `willTransition` and `didTransition` events https://github.com/ember-learn/deprecation-app/pull/192
- [x] Write deprecation guide for Transition state usage https://github.com/ember-learn/deprecation-app/pull/192
- [x] Make Transition public #17040
- [x] Document Transition.from|to #17040
- [x] Document new events #17025
- [x] Add deprecation guides urls #17049

### Out of Scope (For now)
All APIs dealing with the template portion of emberjs/rfcs/pull/95

- Migrate `OutletState` computation to use public `RouteInfos`
      _Note:_ might be tricky because `OutletState` requires things like `connections`
- Migrate `_routePath` computation to use public `RouteInfos`
- Make transitions immutable in Router.js https://github.com/tildeio/router.js/issues/263

**Comment by rwjblue** [comment]
@chadhietala - I merged the deprecation app PR, we should be able to gather the URL's and update the deprecation's to have the `url`.

**Comment by rwjblue** [comment]
🎉 done did it, and released in 3.6.0...
