### ISSUE TITLE
[META] Element Modifier Manager

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#17142]
- [x] Land Glimmer-VM Upgrade that introduce the concept of `ModifierDefinitonState` #17051 
- [ ] Create modifier manager delegate (possibly unify with custom component manager delegate)
- [ ] Update `lookupModifier` on the `RuntimeResolver`
- [ ] Determine if `{{action}}` can/should leverage the public manager
- [ ] Wrap in feature flag
