### ISSUE TITLE
Deprecate Component#isVisible

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#17918]
[RFC #034](https://github.com/emberjs/rfcs/blob/master/text/0324-deprecate-component-isvisible.md) deprecates `Component#isVisible`.

## Tasks
- [ ] make sure the `Component#isVisible` code path triggers a deprecation https://github.com/emberjs/ember.js/pull/17948
  - [x] decide on deprecation id
  - [x] link to deprecation guide (TBD)
  - [x] specify `until` as "4.0.0"
- [ ] annotate API documentation with `@deprecated`. mention `hidden` HTML attribute as an alternative ([Transition Path](https://github.com/emberjs/rfcs/blob/master/text/0324-deprecate-component-isvisible.md#transition-path))

**Comment by locks** [comment]
Deprecation has been shipped.
