### ISSUE TITLE
[Meta] Yarn 2 Support

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19129]
It seems like yarn 2 is the answer to an ever-increasing list of problems, but being on yarn 1, I can't _just upgrade_ yarn.

I tried migrating to yarn 2 in a brand new ember app and have been documenting progress here: https://github.com/NullVoxPopuli/ember-yarn-2/issues/1

Issues reported as a result (not exhaustive, still exploring):
- [ ] https://github.com/volta-cli/volta/issues/812
   - [ ] https://github.com/volta-cli/volta/issues/651
- [ ] https://github.com/ember-cli/ember-cli/issues/9322
- [ ] https://github.com/ember-cli/ember-cli/issues/8164 (most of the work probably here)

Not yet known to be required, but `npx @yarnpkg/doctor` complains about "not real" packages:
- [ ] https://github.com/emberjs/rfcs/pull/284

* Volta issues included here as volta for tool management is a good a happy path for ember + yarn 1 today

**Comment by rwjblue** [comment]
I don't see this as an issue with Ember itself. The right place to track this information is over in the ember-cli meta issue.

**Comment by acorncom** [comment]
Closing this in favor of https://github.com/ember-cli/ember-cli/issues/8164. Unless you meant a different issue @rwjblue ?
