### ISSUE TITLE
Improve API documentation for @ember/debug deprecate

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#20102]
Currently, `deprecate` from `@ember/debug` has very barebones API documentation: https://api.emberjs.com/ember/4.4/functions/@ember%2Fdebug/deprecate.

## Tasks

- [x] Improve `options` type to state which options are supported.
- [ ] Improve description to include information about Ember's deprecation system
- [ ] Add code snippet with example usage. Can be taken from the ember.js source code itself.

**Comment by geneukum** [comment]
I can take a look at this in the next day or two.

**Comment by kirtan-desai** [comment]
Hey, I would like to take this task. Where can I find the documentation file?

**Comment by locks** [comment]
@geneukum @kirtan-desai thank you for your interest! In general a good way to find where a certain function is in the source code is to check the "Defined in:" link in the API docs:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/32344/179192667-8f2c5fed-ccc1-4def-9aba-47b8977d26f1.png"> which in this case links to https://github.com/emberjs/ember.js/blob/v4.4.0/packages/%40ember/debug/lib/deprecate.ts#L181.
There are a couple of cases where the links point to the wrong place, but that should be rare and we should fix it anyway.

**Comment by locks** [comment]
Visiting the page on the API docs I noticed that we are not surfacing what the options object contains, so only the two other tasks remain!

**Comment by geneukum** [comment]
@locks, I think that the other two options may be covered by https://github.com/emberjs/ember.js/pull/20124.

**Comment by GieralZiomal** [comment]
Hi i'd like to help. Where i have to start?

**Comment by legendkartik45** [comment]
I can work on this

**Comment by Blueclaus13** [comment]
Is this issue opened still?

**Comment by RyanMuzzey** [comment]
It looks like #20124 address the remaining issues. Can this be closed or are there further changes needed for the docs?
