### ISSUE TITLE
[draft] RFC 800: TypeScript Adoption Plan Implementation Tracking

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#20162]
(I will fill this out progressively over the course of the next week or two!)

# RFC 0800 Tracking Issue

Implement [RFC 0800: TypeScript Adoption Plan](https://rfcs.emberjs.com/id/0800-ts-adoption-plan).

## Publish types

- [ ] `ember-source`, including:
    - `ember`
    - `@ember/application`
    - `@ember/array`
    - `@ember/component`
    - `@ember/controller`
    - `@ember/debug`
    - `@ember/destroyable`
    - `@ember/engine`
    - `@ember/error`
    - `@ember/helper`
    - `@ember/modifier`
    - `@ember/object`
    - `@ember/ordered-set`
    - `@ember/owner`
    - `@ember/polyfills`
    - `@ember/routing`
    - `@ember/runloop`
    - `@ember/service`
    - `@ember/template`
    - `@ember/test`
    - `@ember/utils`

- [ ] `ember-data`, including:
    - `ember-data`
    - `@ember-data/adapter`
    - `@ember-data/canary-features`
    - `@ember-data/debug`
    - `@ember-data/deprecations`
    - `@ember-data/model`
    - `@ember-data/record-data`
    - `@ember-data/serializer`
    - `@ember-data/store`

- [ ] `@ember/optional-features`: https://github.com/emberjs/ember-optional-features/issues/329

- [ ] `ember-cli`

- [ ] `ember-cli-htmlbars`

- [ ] `ember-page-title`: https://github.com/ember-cli/ember-page-title/issues/239

- [ ] `ember-resolver`: https://github.com/ember-cli/ember-resolver/issues/795

**Comment by bertdeblock** [comment]
FYI, the `ember-cli-sri` repo is archived.

**Comment by bertdeblock** [comment]
@chriskrycho Seems like a part is missing from the `ember-fetch` entry in the list above?

**Comment by chriskrycho** [comment]
Oh, good catches on both points. Updating!

**Comment by ijlee2** [comment]
@chriskrycho @bertdeblock I'd like to help out with `ember-welcome-page`.

I think we need to first update the repo (CI, dependencies, and minimum support for Node & Ember), before we introduce TypeScript, though. This would help with future maintenance.

Is it okay if I temporarily own the project and make a few pull requests to keep the project up-to-date and easy to maintain?

**Comment by chriskrycho** [comment]
Please do! I'll mark is at "taken" here and am happy to help with any TS work there.

**Comment by ijlee2** [comment]
@chriskrycho Thanks!

**Comment by kategengler** [comment]
@emberjs/typescript-core Can this be closed?

**Comment by gitKrystan** [comment]
I think we've completed the high-priority items on this list but not everything. Checking in with @wagenet

**Comment by kategengler** [comment]
@wagenet has agreed this can be closed.
