### ISSUE TITLE
Remove Deprecations Targeted at 5.0

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#20383]
* [x] remove-owner-inject #20382
* [x] deprecate-ember-error #20379
* [x] ember-polyfills.deprecate-assign #20380 
* [x] deprecate-auto-location #20406
* [x] routing.transition-methods #20413
* [x] ember-string.add-package #20381 
* [x] ember-string.htmlsafe-ishtmlsafe #20381
* [x] ember-strings #20381
* [x] ember-string.from-ember-module #20381

**Comment by chriskrycho** [comment]
I have a WIP branch locally for `deprecate-auto-location`. It's a bit more finicky than some of the others, but I will have it up by end of week for sure.

**Comment by chriskrycho** [comment]
It is! Alas, "end of week" did not happen because of 🔥 at work, but it should happen this coming week.

**Comment by wagenet** [comment]
We did it!
