### ISSUE TITLE
Finishing Octane: removing mandatory dependencies for classic features

### ISSUE THREAD

**Issue by MelSumner** [emberjs/ember.js#20472]
Idea: "pay as you go" 

## Goals

- reduce the API surface for idiomatic Polaris apps
- reduce the size of minimum viable payload for Ember apps
- eliminate the entanglements that reduce the benefits of tree-shaking

## Tasks

- [ ] identify list of classic features that are still mandatory dependencies
- [ ] craft an RFC (one RFC? series of RFCs where deps are grouped somehow? one RFC per dep?)
- [ ] create discreet task based on RFC, identifying dep to be removed and its replacement/alternative approach

## Supporting Notes

1. by the time we get to Polaris, no classic feature should be included in `ember new` or `ember addon`
2. If that's bc the files are removed, or if it's because treeshaking, remains to be seen.

**Comment by MelSumner** [comment]
If you are interested in leading/owning this work, please reach out to me on Discord!

**Comment by ef4** [comment]
One way to meet this requirement is to ship ember-source as a v2 addon. V2 addons necessarily shake out unused modules.

(Becoming a v2 addon probably also involves ember-source itself reorganizing some things that are unnecessarily tangled.)

**Comment by kategengler** [comment]
This is likely descoped from Polaris.
