### ISSUE TITLE
Refactor View Layer

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#5261]
* [ ] Resolve issues with `createChildView` - #2903 
* [ ] Allow application view to receive multiple re-renders - #2267
* [ ] Examine className reset issues - #4791

**Comment by mmun** [comment]
I think this issue can be closed and any specific issues re-opened now that Glimmer has landed.
