### ISSUE TITLE
Improve/refactor outlets and view creation

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#5264]
* [ ] `lastRenderedTemplate` should not get polluted - #3119 
* [ ] template rendered into a named template should be able to use own outlet - #4434 
* [ ] support rendering into an outlet created in a template render - #3626 
* [ ] transition to static segment after dynamic should clean content - #3850 
* [ ] avoid unnecessary view re-instantiation when changing model - #4353

**Comment by stefanpenner** [comment]
i think @ef4's recent work sorts most of this out.
