### ISSUE TITLE
Cleanup/refactor container

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#5266]
* [ ] Non singleton injections are treated as a singleton - #3310
* [x] Child containers shouldn't clobber resolver delegation - #4800
* [ ] Do not presume extend is Ember's extend - #4627

**Comment by rwjblue** [comment]
@dgeb - Can you take a look at these items and let us know which were fixed in the recent refactoring?

**Comment by stefanpenner** [comment]
we don't support childContainers so that one is fixed.

the other two depend on a future refactoring to remove the internal extend.

**Comment by dgeb** [comment]
@rwjblue @stefanpenner I can confirm that the `childContainers` issue is the only one that's been addressed. I deliberately tried to avoid changing any other internal behavior while refactoring the APIs. Now that the refactoring is complete, it's a good time to resolve these.

**Comment by rwjblue** [comment]
Significant refactoring has occurred, I think this can be closed for now.
