### ISSUE TITLE
ArrayComputed issues

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#9462]
* [ ] Ember Data relationships and multiple computed.sort CPs can cause error - #4919
* [ ] iterDeps (ember.js#2818, canary) calls "propertyDidChange" on attributes, that were used by Ember.computed.sort - #4231
* [ ] SortableMixin does not work when whole array changes - #3706
* [ ] TypeError for Ember.computed.sort in DependentArraysObserver.prototype.dependentArrayWillChange - #5596
* [ ] Ember computed sort fails with contentIndex property - #9485

**PRs:**
* [ ] Ember.computed.sort Observers - #5150
* [ ] fix reduce computed - #9492

**Comment by Serabe** [comment]
@wagenet I might be one of those people. I'm skimming through the code trying to get to understand it and having a goal might help me.
